[package]
name = 'pathattr'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'pathattr'

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr", branch = "fix_from_iter_collection" }
