# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_pathattr_wrappers", use_symbols = TRUE, package_name = "pathattr")

#' @docType package
#' @usage NULL
#' @useDynLib pathattr, .registration = TRUE
NULL

#' Attribute Paths
#' @param path Character vector. Channels delimited by ">"
#' @param dates Character vector. Dates delimeted by ">"
#' @param value Numeric vector.
#' @param outcome Numeric vector.
#' @param lookup a named list of lookup values. Each element must be a scalar numeric value corresponding to a path value.
#' @export
attr_path <- function(path, dates, value, outcome, lookup) .Call(wrap__attr_path, path, dates, value, outcome, lookup)


# nolint end
